#%RAML 0.8
---
title: Management API - Arion banki Fintech
documentation: 
  - title: About Management - UserManagement
    content: |
      This service contains actions for working with clients and user registration for fintech sandbox.

  - title: Security
    content: |
      Service requests need to contain an API key which approved teams in the hackathon will be able to get through the API portal. 
            
baseUri: https://arionapi-sandbox.azure-api.net/management/{version}
version: v1
mediaType: application/json

traits:  
  - subscribable:
      usage: Include your API subscription.
      headers:
        Ocp-Apim-Subscription-Key:
          description: |
            Used to send a valid subscription key.
          type: string       
          
/clients:
  is: [ subscribable ]
  displayName: Management
  description: Used to register a Client, so the authorization server will recognize and correctly redirect tokens back to the solution.
  post:
    description: Used to register a Client, so the authorization server will recognize and correctly redirect tokens back to the solution.
    queryParameters:
        clientId:
           displayName: The identifier for this client
           type: string 
           required: true
           description: The descriptive but unique identifier for this client.
           example: SomeExample
        redirectpath:
          displayName: Redirectpath
          type: string
          required: true
          description: The redirect path after authentication.
          example: SomeExample
        flowType:
          displayName: Type of OAuth2 flow
          type: string
          required: true
          description: can either be "codeflow" or "implicit".
          example: SomeExample
/users:
  is: [ subscribable ]
  displayName: User Management
  post:
    description: Makes it possible to get a new test user to use in the Fintech party sandbox. Note down the username and password, as it will not be shown again. The ClientID must be registered first.
    queryParameters:
        clientId:
         displayName: The identifier for this client
         type: string 
         required: true
         description: The descriptive but unique identifier for this client.
         example: SomeExample
/rbjwt:
  is: [ subscribable ]
  displayName: RB Json Web Token
  get:
    description: Returns the Jwt token to use with RBs API services.
