#%RAML 0.8
---
title: Currency Rates API - Arion banki Fintech
documentation:
  - title: Um CurrencyRates - Gengisupplýsingar
    content: |
      Undir þessari þjónustu er að finna upplýsingar um skráð gengi eftir tímabilum. Gögn þjónustunnar eiga að endurspegla uppfærða stöðu gengist sem sýnilegt er á heimasíðu Arion banka.

      Hér má skoða [html lýsingu](/Currency.html "sjá Currency.html") á samningnum í GitHub repo fyrir Fintech partý.
  - title: Öryggi
    content: |
      Köll á þjónustuna þurfa að innihalda API lykil sem samþykkt teymi í Fintech Party munu geta sótt um á gátt API viðmótsins. Að öðru leiti er þjónustan ekki varin auðkenningu eða kallar á frekari heimildir.
baseUri: https://arionapi-sandbox.azure-api.net/currency/{version}
version: v1
mediaType: application/json

traits:  
  - subscribable:
      usage: Include your API subscription.
      headers:
        Ocp-Apim-Subscription-Key:
          description: |
            Used to send a valid subscription key.
          type: string    
  - pageable:
      queryParameters:
        offset:
          description: Hlaupa yfir tiltekin fjölda færslna með því að tilgreina hliðrun
          type: integer
          required: false
          example: 20
          default: 0
        limit:
          description: Takmarka fjölda færslna í svari
          type: integer
          required: false
          example: 80
          default: 10

schemas:
  - currencyWithBuyAndSellRateCollection: |
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "properties": {
        "totalCount": {
            "type": "integer",
            "comment": "The total count of transaction available by selection. If 0, then",
            "description": "Fjöldi færslna í sem hægt er að sækja."
        },
        "currencyWithBuyAndSellRate": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                  "currencyCode": {
                    "type": "string",
                    "required": true,
                    "description": "Currency code."
                  },
                  "currencyTypeName": {
                    "enum": [ "CentralBankRate", "ValitorRate", "BorgunRate" ],
                    "required": true,
                    "description": "Descriptive name for the type."
                  },
                  "timestamp": {
                    "type": "string",
                    "format": "date-time",
                    "required": true,
                    "description": "Timestamp when the currency was valid."
                  },
                  "buyRate": {
                    "type": "number",
                    "required": true,
                    "description": "Buy rate."
                  },
                  "sellRate": {
                    "type": "number",
                    "required": true,
                    "description": "Selling rate."
                  },
                  "midRate": {
                    "type": "number",
                    "required": false,
                    "description": "Mid rate."
                  }
                }
             }
          }
        }
      }

/currencyRates:
  is: [ subscribable ]
  displayName: Currencies
  get:
    description: Returns information about available currency exhange rates
    responses:
      200:
        body:
          example: |
            [
              {
                "CentralBankRate"
              },
              {
                "ValitorRate"
              },
              {
                ",
              {
                "ValitorRate"
              }"
              }
            ]
  /{currencyTypeName}:
    is: [ subscribable ]
    displayName: CurrencyTypeName
    get:
      description: Returns information about a particular exchange rate
      responses:
        200:
          body:
              application/json:
                    schema: currencyWithBuyAndSellRateCollection